server:
  port: 8092

spring:

  #DB
  datasource:
    url: jdbc:mysql://mysqldb:3306/todos?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: secret
    platform: mysql

  #JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        use_sql_comments: false
        format_sql: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

Feign:
  circuitbreaker:
    enabled: true

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'

management:
  endpoints:
    web:
      exposure:
        include: '*'