version: '3.7'

services:
  app:
    image: 'coach-service:latest'
    build:
      context: .
    working_dir: /app
    container_name: app
    depends_on:
      - db
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_PORT: 3306
      #- SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/to do
      #- SPRING_DATASOURCE_USERNAME=root
      #- SPRING_DATASOURCE_PASSWORD=secret
      #- SPRING_JPA_HIBERNATE_DDL_AUTO=update
      #- SPRING_JPA_SHOW_SQL=true
    ports:
      - 8092:8092

  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - todo-mysql-data:/var/lib/mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todo
volumes:
  todo-mysql-data: